#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: MZR
main: net.peacefulcraft.templateus.mzr
version: 0.0.1
api-version: 1.16
website: https://www.peacefulcraft.net/
depend: []
softdepend: []

commands:
  mzradmin:
    aliases: [ 'mzra' ]
    description: MZR Administration and Setup
    permission-message:  Permission mzr.admin is required to use this command
    usage: /<command> to use the example command.

permissions:
  mzr.admin:
    description: Gives access to all MZR commands
